### ISSUE TITLE
Build failures in Windows Release leg

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/symreader#236]
The [official builds](https://dev.azure.com/dnceng/internal/_build?definitionId=289&_a=summary) (Internal link) have been failing for some time now.  The failure is only in the Windows Release leg.

**Failure snippet**

```
Creating build manifest file 'F:\workspace\_work\1\s\artifacts\log\Release\AssetManifest\Windows_NT-AnyCPU.xml'...
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error : The following files have conflicting FileSignInfo entries: Microsoft.DiaSymReader.dll
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error :    at Microsoft.DotNet.VersionTools.BuildManifest.Model.SigningInformationParsingExtensions.ThrowIfInvalidFileSignInfo(IEnumerable`1 fileSignInfo) in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationParsingExtensions.cs:line 116
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error :    at Microsoft.DotNet.VersionTools.BuildManifest.Model.SigningInformationModel.ToXml() in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationModel.cs:line 35
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error :    at Microsoft.DotNet.VersionTools.BuildManifest.Model.BuildModel.ToXml() in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BuildModel.cs:line 28
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BuildManifestUtil.WriteAsXml(BuildModel buildModel, String filePath, TaskLoggingHelper log) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs:line 74
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PushToAzureDevOpsArtifacts.Execute() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs:line 67
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20630.2\tools\Publish.proj(151,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) The following files have conflicting FileSignInfo entries: Microsoft.DiaSymReader.dll
   at Microsoft.DotNet.VersionTools.BuildManifest.Model.SigningInformationParsingExtensions.ThrowIfInvalidFileSignInfo(IEnumerable`1 fileSignInfo) in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationParsingExtensions.cs:line 116
   at Microsoft.DotNet.VersionTools.BuildManifest.Model.SigningInformationModel.ToXml() in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationModel.cs:line 35
   at Microsoft.DotNet.VersionTools.BuildManifest.Model.BuildModel.ToXml() in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BuildModel.cs:line 28
   at Microsoft.DotNet.Build.Tasks.Feed.BuildManifestUtil.WriteAsXml(BuildModel buildModel, String filePath, TaskLoggingHelper log) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs:line 74
   at Microsoft.DotNet.Build.Tasks.Feed.PushToAzureDevOpsArtifacts.Execute() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs:line 67
```

**Comment by MichaelSimons** [comment]
This failure is blocking the [source-build through arcade feature work](https://github.com/mono/linker/pull/1823)

cc @tmat

**Comment by tmat** [comment]
IDK, nothing has changed in this repo for quite a while.

**Comment by MichaelSimons** [comment]
@tmat, It looks like the build started failing when a new Arcade version was taken back in Feb.  The build failure looks related to some signing validation which was added with https://github.com/dotnet/arcade/pull/6594 (specifically [this change](https://github.com/dotnet/arcade/pull/6594/files#diff-6af0f8adc6564423213ffc072db12ce7fa279d2101076c8c7887af4be10352a2R24)).  Please work with Engineering Services to resolve this issue.  Perhaps @mmitche could provide some insight since he worked on the changes.

**Comment by mmitche** [comment]
It's validation of the input manifest. So when doing the PushToAzureDevOps artifacts here, it makes up a manifest using the FileSignInfo (and other) itemgroups. It means that there are two elements for Microsoft.DiaSymReader.dll in that itemgroup and they have different certificates listed. Previously this would have been just ignored, and the last item in the itemgroup would have won, but that introduces interesting problems when dealing with a merged manifest. In that case, the last leg to finish would win.

Looking at symreader's spec, it looks fine, which is odd. Odder still, there is an exact test for this in arcade already (sign infos contain different TFMs but same pkt) and that passing. Digging deeper.

**Comment by MichaelSimons** [comment]
The underlying [Arcade issue](https://github.com/dotnet/arcade/issues/7064) was fixed.  Waiting on the new version to get picked up here.

**Comment by MichaelSimons** [comment]
This was fixed with https://github.com/dotnet/symreader/pull/239.
